# Generated by Django 5.0 on 2024-01-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_etudiant', models.IntegerField()),
                ('id_cours', models.IntegerField()),
                ('nombre_heures_absence', models.IntegerField()),
                ('date_absence', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id_cours', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_cours', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id_etudiant', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
            ],
        ),
    ]
